import { BlocksMetadata, categoryIds } from "./declarations";

export const blocksMetadata: BlocksMetadata[] = [
  {
    id: "file-upload-01",
    category: categoryIds.FileUpload,
    name: "File Upload with Preview",
    iframeHeight: "506px",
    type: "directory",
  },
  {
    id: "file-upload-02",
    category: categoryIds.FileUpload,
    name: "Simple File Upload",
    iframeHeight: "460px",
    type: "file",
  },
  {
    id: "file-upload-03",
    category: categoryIds.FileUpload,
    name: "Multi-File Dropzone",
    iframeHeight: "685px",
    type: "file",
  },
  {
    id: "file-upload-04",
    category: categoryIds.FileUpload,
    name: "Drag & Drop Upload",
    iframeHeight: "550px",
    type: "file",
  },
  {
    id: "file-upload-05",
    category: categoryIds.FileUpload,
    name: "File Upload with Progress",
    iframeHeight: "430px",
    type: "file",
  },

  {
    id: "form-layout-01",
    category: categoryIds.FormLayout,
    name: "Workspace Registration Form",
    iframeHeight: "585px",
    type: "file",
  },
  {
    id: "form-layout-02",
    category: categoryIds.FormLayout,
    name: "Form Sections with Side Labels",
    iframeHeight: "920px",
    type: "file",
  },
  {
    id: "form-layout-03",
    category: categoryIds.FormLayout,
    name: "Form Sections with Checkbox Settings",
    iframeHeight: "1060px",
    type: "file",
  },
  {
    id: "form-layout-04",
    category: categoryIds.FormLayout,
    name: "Early Access Application with Package Selection",
    iframeHeight: "800px",
    type: "file",
  },
  {
    id: "form-layout-05",
    category: categoryIds.FormLayout,
    name: "Design Workspace Creation with Plan Selection",
    iframeHeight: "1230px",
    type: "file",
  },

  {
    id: "login-01",
    category: categoryIds.Login,
    name: "Simple Email Login with Google",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "login-02",
    category: categoryIds.Login,
    name: "Simple Email/Password Login with Google",
    iframeHeight: "500px",
    type: "file",
  },
  {
    id: "login-03",
    category: categoryIds.Login,
    name: "Simple Email/Password Login",
    iframeHeight: "420px",
    type: "file",
  },
  {
    id: "login-04",
    category: categoryIds.Login,
    name: "Simple Login with Social Buttons",
    iframeHeight: "620px",
    type: "file",
  },
  {
    id: "login-05",
    category: categoryIds.Login,
    name: "Simple Card Signup Form",
    iframeHeight: "750px",
    type: "file",
  },
  {
    id: "login-06",
    category: categoryIds.Login,
    name: "Login with Magic Link/SSO",
    iframeHeight: "700px",
    type: "file",
  },
  {
    id: "login-07",
    category: categoryIds.Login,
    name: "Full Page Login with Icons",
    iframeHeight: "700px",
    type: "file",
  },
  {
    id: "login-08",
    category: categoryIds.Login,
    name: "Login with SSO",
    iframeHeight: "680px",
    type: "file",
  },
  {
    id: "login-09",
    category: categoryIds.Login,
    name: "Signup with Role Selection",
    iframeHeight: "880px",
    type: "file",
  },

  {
    id: "stats-01",
    category: categoryIds.Stats,
    name: "Stats with trending",
    iframeHeight: "200px",
    type: "file",
  },
  {
    id: "stats-02",
    category: categoryIds.Stats,
    name: "Stats with borders",
    iframeHeight: "200px",
    type: "file",
  },
  {
    id: "stats-03",
    category: categoryIds.Stats,
    name: "Stats cards",
    iframeHeight: "220px",
    type: "file",
  },
  {
    id: "stats-04",
    category: categoryIds.Stats,
    name: "Stats cards with badges",
    iframeHeight: "200px",
    type: "file",
  },
  {
    id: "stats-05",
    category: categoryIds.Stats,
    name: "Stats cards with links",
    iframeHeight: "240px",
    type: "file",
  },
  {
    id: "stats-06",
    category: categoryIds.Stats,
    name: "Stats cards with status",
    iframeHeight: "270px",
    type: "file",
  },
  {
    id: "stats-07",
    category: categoryIds.Stats,
    name: "Stats cards with circular progress",
    iframeHeight: "280px",
    type: "file",
  },
  {
    id: "stats-08",
    category: categoryIds.Stats,
    name: "Stats card with circular progress and links",
    iframeHeight: "240px",
    type: "file",
  },
  {
    id: "stats-09",
    category: categoryIds.Stats,
    name: "Stats card with progress",
    iframeHeight: "230px",
    type: "file",
  },
  {
    id: "stats-10",
    category: categoryIds.Stats,
    name: "Stats card with area chart",
    iframeHeight: "220px",
    type: "file",
  },

  {
    id: "grid-list-01",
    category: categoryIds.GridList,
    name: "Simple Card with Dropdown",
    iframeHeight: "200px",
    type: "file",
  },
  {
    id: "grid-list-02",
    category: categoryIds.GridList,
    name: "Link cards",
    iframeHeight: "250px",
    type: "file",
  },
  {
    id: "grid-list-03",
    category: categoryIds.GridList,
    name: "Link cards with icons",
    iframeHeight: "500px",
    type: "file",
  },

  {
    id: "dialog-01",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "350px",
    type: "file",
  },
  {
    id: "dialog-02",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "350px",
    type: "file",
  },
  {
    id: "dialog-03",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "dialog-04",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "350px",
    type: "file",
  },
  {
    id: "dialog-05",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "dialog-06",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "450px",
    type: "file",
  },
  {
    id: "dialog-07",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "450px",
    type: "file",
  },
  {
    id: "dialog-08",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "600px",
    type: "file",
  },
  {
    id: "dialog-09",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "350px",
    type: "file",
  },
  {
    id: "dialog-10",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "750px",
    type: "file",
  },
  {
    id: "dialog-11",
    category: categoryIds.Dialogs,
    name: "Dialog",
    iframeHeight: "650px",
    type: "file",
  },
  {
    id: "dialog-12",
    category: categoryIds.Dialogs,
    name: "Dialog with avatar upload",
    iframeHeight: "650px",
    type: "file",
  },
];
