import * as components from "./components";

export const blocksComponents: { [blocksId: string]: React.ElementType } = {
  "file-upload-01": components.FileUpload01,
  "file-upload-02": components.FileUpload02,
  "file-upload-03": components.FileUpload03,
  "file-upload-04": components.FileUpload04,
  "file-upload-05": components.FileUpload05,

  "form-layout-01": components.FormLayout01,
  "form-layout-02": components.FormLayout02,
  "form-layout-03": components.FormLayout03,
  "form-layout-04": components.FormLayout04,
  "form-layout-05": components.FormLayout05,

  "login-01": components.Login01,
  "login-02": components.Login02,
  "login-03": components.Login03,
  "login-04": components.Login04,
  "login-05": components.Login05,
  "login-06": components.Login06,
  "login-07": components.Login07,
  "login-08": components.Login08,
  "login-09": components.Login09,

  "stats-01": components.Stats01,
  "stats-02": components.Stats02,
  "stats-03": components.Stats03,
  "stats-04": components.Stats04,
  "stats-05": components.Stats05,
  "stats-06": components.Stats06,
  "stats-07": components.Stats07,
  "stats-08": components.Stats08,
  "stats-09": components.Stats09,
  "stats-10": components.Stats10,

  "grid-list-01": components.GridList01,
  "grid-list-02": components.GridList02,
  "grid-list-03": components.GridList03,

  "dialog-01": components.Dialog01,
  "dialog-02": components.Dialog02,
  "dialog-03": components.Dialog03,
  "dialog-04": components.Dialog04,
  "dialog-05": components.Dialog05,
  "dialog-06": components.Dialog06,
  "dialog-07": components.Dialog07,
  "dialog-08": components.Dialog08,
  "dialog-09": components.Dialog09,
  "dialog-10": components.Dialog10,
  "dialog-11": components.Dialog11,
  "dialog-12": components.Dialog12,
};
